package com.horabase.api.incident;
import com.horabase.api.attendance.*; import com.horabase.api.business.*; import com.horabase.api.employee.*; import com.horabase.api.incident.dto.*; import com.horabase.api.shift.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDate; import java.util.*;
@Service public class AttendanceIncidentService{
 private final AttendanceIncidentRepository repo; private final BusinessRepository businesses; private final EmployeeRepository employees; private final ShiftRepository shifts; private final AttendanceRepository attendances;
 public AttendanceIncidentService(AttendanceIncidentRepository r,BusinessRepository b,EmployeeRepository e,ShiftRepository s,AttendanceRepository a){repo=r;businesses=b;employees=e;shifts=s;attendances=a;}
 @Transactional public IncidentResponse create(Long bid,IncidentRequest q){Business b=businesses.findById(bid).orElseThrow(()->notFound("comercio")); Employee e=employees.findByIdAndBusiness_Id(q.employeeId(),bid).orElseThrow(()->notFound("empleado")); Shift s=q.shiftId()==null?null:shifts.findByIdAndBusiness_Id(q.shiftId(),bid).orElseThrow(()->notFound("turno")); Attendance a=q.attendanceId()==null?null:attendances.findDetailedByIdAndBusinessId(q.attendanceId(),bid).orElseThrow(()->notFound("asistencia")); if(s!=null&&!s.getEmployee().getId().equals(e.getId())||a!=null&&!a.getEmployee().getId().equals(e.getId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El turno o asistencia no pertenece al empleado"); AttendanceIncident i=new AttendanceIncident();i.setBusiness(b);i.setEmployee(e);i.setShift(s);i.setAttendance(a);i.setIncidentDate(q.incidentDate());i.setType(q.type());i.setDetectedMinutes(q.detectedMinutes());i.setNotes(norm(q.notes()));i.setStatus(IncidentStatus.DETECTED);return out(repo.save(i));}
 @Transactional(readOnly=true) public List<IncidentResponse> list(Long bid,LocalDate from,LocalDate to,Long eid){businesses.findById(bid).orElseThrow(()->notFound("comercio"));if(to.isBefore(from))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El período no es válido");return(eid==null?repo.findAllByBusiness_IdAndIncidentDateBetweenOrderByIncidentDateDesc(bid,from,to):repo.findAllByBusiness_IdAndEmployee_IdAndIncidentDateBetweenOrderByIncidentDateDesc(bid,eid,from,to)).stream().map(this::out).toList();}
 @Transactional public IncidentResponse resolve(Long bid,Long id,ResolveIncidentRequest q){if(q.status()==IncidentStatus.DETECTED)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El estado de resolución no es válido");AttendanceIncident i=repo.findByIdAndBusiness_Id(id,bid).orElseThrow(()->notFound("incidencia"));i.setStatus(q.status());String n=norm(q.notes());if(n!=null)i.setNotes(i.getNotes()==null?n:i.getNotes()+System.lineSeparator()+n);return out(repo.save(i));}
 private ResponseStatusException notFound(String x){return new ResponseStatusException(HttpStatus.NOT_FOUND,"No se encontró el "+x);} private String norm(String x){return x==null||x.isBlank()?null:x.trim();}
 private IncidentResponse out(AttendanceIncident i){Employee e=i.getEmployee();return new IncidentResponse(i.getId(),i.getBusiness().getId(),e.getId(),e.getFirstName()+" "+e.getLastName(),i.getShift()==null?null:i.getShift().getId(),i.getAttendance()==null?null:i.getAttendance().getId(),i.getIncidentDate(),i.getType(),i.getStatus(),i.getDetectedMinutes(),i.getNotes(),i.getCreatedAt(),i.getUpdatedAt());}
}
