import { ArrowDownToLine, ArrowUpFromLine, CheckCircle2, Settings2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Brand } from '../components/Brand'
import { Notice } from '../components/Feedback'
import { Modal } from '../components/Modal'
import { api } from '../lib/api'
import { formatDateTime } from '../lib/format'
import type { Attendance } from '../types'

interface Device { businessId: string; terminalId: string; secret: string }
const KEY = 'horabase.terminal'
function loadDevice(): Device { try { return JSON.parse(localStorage.getItem(KEY) ?? '') as Device } catch { return { businessId: '', terminalId: '', secret: '' } } }

export function KioskPage() {
  const [device, setDevice] = useState(loadDevice); const [settings, setSettings] = useState(!device.secret); const [employeeId, setEmployeeId] = useState(''); const [result, setResult] = useState<Attendance | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [now, setNow] = useState(new Date())
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer) }, [])
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next = { businessId: String(data.get('businessId')), terminalId: String(data.get('terminalId')), secret: String(data.get('secret')) }; localStorage.setItem(KEY, JSON.stringify(next)); setDevice(next); setSettings(false); setError('') }
  async function mark(type: 'check-in' | 'check-out') { setBusy(true); setResult(null); setError(''); try { setResult(await api<Attendance>(`/api/terminal/businesses/${device.businessId}/${type}`, { method: 'POST', body: JSON.stringify({ employeeId: Number(employeeId) }), headers: { 'X-Terminal-Id': device.terminalId, 'X-Terminal-Secret': device.secret } })); setEmployeeId('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo registrar la marcación') } finally { setBusy(false) } }
  return <main className="kiosk-page"><header><Brand /><button className="icon-button" onClick={() => setSettings(true)} aria-label="Configurar terminal"><Settings2 /></button></header><section className="kiosk-clock"><span>{now.toLocaleDateString('es-UY', { weekday: 'long', day: 'numeric', month: 'long' })}</span><strong>{now.toLocaleTimeString('es-UY', { hour: '2-digit', minute: '2-digit' })}</strong><p>Ingresá tu número interno para registrar la jornada.</p></section><section className="kiosk-card">{error && <Notice message={error} />}{result && <div className="kiosk-success"><CheckCircle2 /><div><strong>Marcación registrada</strong><span>{result.employeeName} · {formatDateTime(result.checkOutAt ?? result.checkInAt)}</span></div></div>}<label>ID de empleado<input inputMode="numeric" autoFocus value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} placeholder="Ej. 24" /></label><div className="kiosk-actions"><button className="button check-in" disabled={busy || !employeeId || !device.secret} onClick={() => mark('check-in')}><ArrowDownToLine /> Marcar entrada</button><button className="button check-out" disabled={busy || !employeeId || !device.secret} onClick={() => mark('check-out')}><ArrowUpFromLine /> Marcar salida</button></div>{!device.secret && <p className="muted">Esta terminal todavía no está configurada.</p>}</section><footer>Terminal {device.terminalId || 'sin configurar'} · HoraBase</footer>{settings && <Modal title="Configurar terminal" onClose={() => setSettings(false)}><form className="form-stack" onSubmit={save}><p className="muted">Usá las credenciales generadas por un administrador.</p><label>ID del comercio<input name="businessId" inputMode="numeric" defaultValue={device.businessId} required /></label><label>Identificador de terminal<input name="terminalId" defaultValue={device.terminalId} required /></label><label>Secreto<input name="secret" type="password" defaultValue={device.secret} required /></label><div className="modal-actions"><button className="button primary">Guardar en este dispositivo</button></div></form></Modal>}</main>
}
