import { ArrowRight, Building2, Clock3, ShieldCheck } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { Brand } from '../components/Brand'
import { Notice } from '../components/Feedback'

export function LoginPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [businessId, setBusinessId] = useState(''); const [document, setDocument] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  if (auth.token) return <Navigate to={auth.user.mustChangePassword ? '/cambiar-contrasena' : auth.user.role === 'ADMIN' ? '/admin' : '/mi'} replace />
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const user = await auth.login(businessId ? Number(businessId) : null, document, password); navigate(user.mustChangePassword ? '/cambiar-contrasena' : user.role === 'ADMIN' ? '/admin' : '/mi') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo iniciar sesión') } finally { setLoading(false) } }
  return <main className="login-page"><section className="login-story"><Brand /><div className="story-copy"><span className="eyebrow light">Gestión que marca la diferencia</span><h1>Tu equipo,<br />en su mejor horario.</h1><p>Turnos claros, asistencia confiable y decisiones simples para cada jornada.</p><div className="story-points"><span><Clock3 /> Horarios en tiempo real</span><span><ShieldCheck /> Información protegida</span><span><Building2 /> Diseñado para comercios</span></div></div><small>HoraBase · Gestión de personas sin vueltas</small></section><section className="login-panel"><form className="auth-card" onSubmit={submit}><div><span className="eyebrow">Bienvenido</span><h2>Ingresá a HoraBase</h2><p>Usá tus datos de acceso para continuar.</p></div>{error && <Notice message={error} />}<label>Comercio <input inputMode="numeric" value={businessId} onChange={(event) => setBusinessId(event.target.value)} placeholder="ID del comercio (opcional)" /></label><label>Documento <input autoComplete="username" required value={document} onChange={(event) => setDocument(event.target.value)} placeholder="Ej. 4.567.890-1" /></label><label>Contraseña <input type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tu contraseña" /></label><button className="button primary wide" disabled={loading}>{loading ? 'Ingresando…' : <>Ingresar <ArrowRight size={18} /></>}</button><p className="auth-help">¿Olvidaste tu contraseña? Contactá al administrador de tu comercio.</p></form></section></main>
}
