package com.horabase.api.request;
import com.horabase.api.auth.CurrentUser;import com.horabase.api.business.*;import com.horabase.api.employee.*;import com.horabase.api.request.dto.*;import com.horabase.api.shift.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@Service public class EmployeeRequestService{private final EmployeeRequestRepository repo;private final BusinessRepository businesses;private final EmployeeRepository employees;private final ShiftRepository shifts;private final Clock clock;public EmployeeRequestService(EmployeeRequestRepository r,BusinessRepository b,EmployeeRepository e,ShiftRepository s,Clock c){repo=r;businesses=b;employees=e;shifts=s;clock=c;}
 @Transactional public EmployeeRequestResponse create(CurrentUser u,CreateEmployeeRequest q){if(u.employeeId()==null)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Solo los empleados pueden crear solicitudes");Business b=businesses.findById(u.businessId()).orElseThrow(()->nf());Employee e=employees.findByIdAndBusiness_Id(u.employeeId(),u.businessId()).orElseThrow(()->nf());Shift s=q.shiftId()==null?null:shifts.findByIdAndBusiness_Id(q.shiftId(),u.businessId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No se encontró el turno"));if(s!=null&&!s.getEmployee().getId().equals(e.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"El turno no pertenece al empleado");EmployeeRequest r=new EmployeeRequest();r.setBusiness(b);r.setEmployee(e);r.setShift(s);r.setType(q.type());r.setTitle(q.title().trim());r.setDescription(q.description().trim());r.setRelatedDate(q.relatedDate());r.setStatus(EmployeeRequestStatus.PENDING);return out(repo.save(r));}
 @Transactional(readOnly=true)public List<EmployeeRequestResponse>mine(CurrentUser u){if(u.employeeId()==null)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"La cuenta no pertenece a un empleado");return repo.findAllByBusiness_IdAndEmployee_IdOrderByCreatedAtDesc(u.businessId(),u.employeeId()).stream().map(this::out).toList();}
 @Transactional(readOnly=true)public List<EmployeeRequestResponse>list(Long bid,EmployeeRequestStatus status){businesses.findById(bid).orElseThrow(()->nf());return(status==null?repo.findAllByBusiness_IdOrderByCreatedAtDesc(bid):repo.findAllByBusiness_IdAndStatusOrderByCreatedAtAsc(bid,status)).stream().map(this::out).toList();}
 @Transactional(readOnly=true)public List<EmployeeRequestResponse>listForEmployee(Long bid,Long eid){employees.findByIdAndBusiness_Id(eid,bid).orElseThrow(()->nf());return repo.findAllByBusiness_IdAndEmployee_IdOrderByCreatedAtDesc(bid,eid).stream().map(this::out).toList();}
 @Transactional public EmployeeRequestResponse resolve(Long bid,Long id,EmployeeRequestStatus status,ResolveEmployeeRequest q){if(status!=EmployeeRequestStatus.APPROVED&&status!=EmployeeRequestStatus.REJECTED)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"La resolución no es válida");EmployeeRequest r=repo.findByIdAndBusiness_Id(id,bid).orElseThrow(()->nf());if(r.getStatus()!=EmployeeRequestStatus.PENDING)throw new ResponseStatusException(HttpStatus.CONFLICT,"La solicitud ya fue resuelta");r.setStatus(status);r.setAdminResponse(q.response().trim());r.setResolvedAt(OffsetDateTime.now(clock));return out(repo.save(r));}
 @Transactional public EmployeeRequestResponse cancel(CurrentUser u,Long id){EmployeeRequest r=repo.findByIdAndBusiness_Id(id,u.businessId()).filter(x->x.getEmployee().getId().equals(u.employeeId())).orElseThrow(()->nf());if(r.getStatus()!=EmployeeRequestStatus.PENDING)throw new ResponseStatusException(HttpStatus.CONFLICT,"Solo se pueden cancelar solicitudes pendientes");r.setStatus(EmployeeRequestStatus.CANCELLED);r.setResolvedAt(OffsetDateTime.now(clock));return out(repo.save(r));}
 private ResponseStatusException nf(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"No se encontró la solicitud");}private EmployeeRequestResponse out(EmployeeRequest r){Employee e=r.getEmployee();return new EmployeeRequestResponse(r.getId(),r.getBusiness().getId(),e.getId(),e.getFirstName()+" "+e.getLastName(),r.getType(),r.getTitle(),r.getDescription(),r.getShift()==null?null:r.getShift().getId(),r.getRelatedDate(),r.getStatus(),r.getAdminResponse(),r.getResolvedAt(),r.getCreatedAt(),r.getUpdatedAt());}}
