import { ArrowLeft, BriefcaseBusiness, CalendarDays, Clock3, Mail, Phone } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Loading, Notice } from '../../components/Feedback'
import { PageHeader } from '../../components/PageHeader'
import { StatusBadge } from '../../components/StatusBadge'
import { useAuth } from '../../auth/AuthContext'
import { useApiData } from '../../hooks/useApi'
import { formatDate, formatDateTime, money, minutes } from '../../lib/format'
import type { EmployeeProfile } from '../../types'

export function EmployeeProfilePage() {
  const { employeeId } = useParams(); const { user } = useAuth(); const profile = useApiData<EmployeeProfile>(`/api/businesses/${user.businessId}/employees/${employeeId}/profile`, {} as EmployeeProfile)
  if (profile.loading) return <Loading />; if (profile.error) return <Notice message={profile.error} />; const employee = profile.data.employee
  return <div className="page"><Link to="/admin/empleados" className="back-link"><ArrowLeft size={17} /> Volver a empleados</Link><PageHeader eyebrow={employee.sectorName} title={`${employee.firstName} ${employee.lastName}`} description={`Ingresó el ${formatDate(employee.hireDate)}`} actions={<StatusBadge status={employee.active ? 'CONFIRMED' : 'CANCELLED'} />} /><section className="profile-hero panel"><div className="avatar xl">{employee.firstName[0]}{employee.lastName[0]}</div><div><h2>{employee.firstName} {employee.lastName}</h2><p><Mail size={16} /> {employee.email}</p><p><Phone size={16} /> {employee.phone || 'Sin teléfono'}</p></div><div className="profile-facts"><span><BriefcaseBusiness />{employee.sectorName}</span><span><Clock3 />{employee.weeklyHours} h semanales</span><span><CalendarDays />Desde {formatDate(employee.hireDate)}</span></div></section><section className="mini-metrics"><div><span>Valor hora</span><strong>{money(employee.hourlyRate)}</strong></div><div><span>Valor hora extra</span><strong>{money(employee.overtimeHourlyRate)}</strong></div><div><span>Documento</span><strong>{employee.document}</strong></div></section><div className="two-columns"><section className="panel"><div className="panel-head"><h2>Próximos turnos</h2></div>{profile.data.upcomingShifts.slice(0, 5).map((shift) => <div className="simple-row" key={shift.id}><div><strong>{formatDateTime(shift.startsAt)}</strong><small>{shift.sectorName}</small></div><span>{minutes(shift.plannedWorkMinutes)}</span></div>)}</section><section className="panel"><div className="panel-head"><h2>Asistencias recientes</h2></div>{profile.data.recentAttendances.slice(-5).reverse().map((attendance) => <div className="simple-row" key={attendance.id}><div><strong>{formatDateTime(attendance.checkInAt)}</strong><small>{minutes(attendance.workedMinutes)}</small></div><StatusBadge status={attendance.status} /></div>)}</section><section className="panel"><div className="panel-head"><h2>Horas extra</h2></div>{profile.data.recentOvertime.slice(0, 5).map((item) => <div className="simple-row" key={item.id}><div><strong>{formatDate(item.workDate)}</strong><small>{minutes(item.approvedMinutes ?? item.detectedMinutes)}</small></div><StatusBadge status={item.status} /></div>)}</section><section className="panel"><div className="panel-head"><h2>Solicitudes</h2></div>{profile.data.requests.slice(0, 5).map((request) => <div className="simple-row" key={request.id}><div><strong>{request.title}</strong><small>{request.description}</small></div><StatusBadge status={request.status} /></div>)}</section></div></div>
}
