import { Plus, Search, UserRound } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../auth/AuthContext'
import { Empty, Loading, Notice } from '../../components/Feedback'
import { Modal } from '../../components/Modal'
import { PageHeader } from '../../components/PageHeader'
import { StatusBadge } from '../../components/StatusBadge'
import { useApiData } from '../../hooks/useApi'
import { api } from '../../lib/api'
import type { Employee, Sector } from '../../types'

export function EmployeesPage() {
  const { token, user } = useAuth(); const bid = user.businessId; const employees = useApiData<Employee[]>(`/api/businesses/${bid}/employees`, []); const sectors = useApiData<Sector[]>(`/api/businesses/${bid}/sectors`, []); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const filtered = useMemo(() => employees.data.filter((item) => `${item.firstName} ${item.lastName} ${item.sectorName}`.toLowerCase().includes(query.toLowerCase())), [employees.data, query])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const values = new FormData(event.currentTarget); try { await api(`/api/businesses/${bid}/employees`, { method: 'POST', body: JSON.stringify({ firstName: values.get('firstName'), lastName: values.get('lastName'), document: values.get('document'), email: values.get('email'), temporaryPassword: values.get('password'), phone: values.get('phone') || null, sectorId: Number(values.get('sectorId')), hireDate: values.get('hireDate'), hourlyRate: Number(values.get('hourlyRate')), overtimeHourlyRate: Number(values.get('overtimeHourlyRate')), weeklyHours: Number(values.get('weeklyHours')) }), headers: { 'Content-Type': 'application/json' } }, token); setOpen(false); await employees.reload() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo crear') } }
  return <div className="page"><PageHeader eyebrow="Personas" title="Empleados" description="Información laboral y acceso de todo el equipo." actions={<button className="button primary" onClick={() => setOpen(true)}><Plus size={18} /> Nuevo empleado</button>} /><div className="toolbar"><label className="search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre o sector" /></label><span>{filtered.length} empleados</span></div>{employees.loading ? <Loading /> : filtered.length === 0 ? <Empty title="Sin resultados" text="Creá el primer empleado o cambiá la búsqueda." /> : <div className="card-grid employees-grid">{filtered.map((employee) => <Link className="employee-card" to={`/admin/empleados/${employee.id}`} key={employee.id}><div className="avatar large">{employee.firstName[0]}{employee.lastName[0]}</div><div className="employee-main"><strong>{employee.firstName} {employee.lastName}</strong><span>{employee.sectorName}</span><small>{employee.email}</small></div><StatusBadge status={employee.active ? 'CONFIRMED' : 'CANCELLED'} /><UserRound className="card-arrow" /></Link>)}</div>}{open && <Modal title="Nuevo empleado" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={create}>{error && <div className="full"><Notice message={error} /></div>}<label>Nombre<input name="firstName" required /></label><label>Apellido<input name="lastName" required /></label><label>Documento<input name="document" required /></label><label>Correo<input name="email" type="email" required /></label><label>Contraseña temporal<input name="password" type="password" minLength={8} required /></label><label>Teléfono<input name="phone" /></label><label>Sector<select name="sectorId" required>{sectors.data.filter((s) => s.active).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Fecha de ingreso<input name="hireDate" type="date" required /></label><label>Valor hora<input name="hourlyRate" type="number" min="0" step="0.01" required /></label><label>Valor hora extra<input name="overtimeHourlyRate" type="number" min="0" step="0.01" required /></label><label>Carga semanal<input name="weeklyHours" type="number" min="0.01" max="168" step="0.25" required /></label><div className="modal-actions full"><button type="button" className="button ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="button primary">Crear empleado</button></div></form></Modal>}</div>
}
