import { CheckCircle2, Plus } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useAuth } from '../../auth/AuthContext'
import { Empty, Loading, Notice } from '../../components/Feedback'
import { Modal } from '../../components/Modal'
import { PageHeader } from '../../components/PageHeader'
import { StatusBadge } from '../../components/StatusBadge'
import { useApiData } from '../../hooks/useApi'
import { api } from '../../lib/api'
import { formatDate, minutes } from '../../lib/format'
import type { Employee, Incident } from '../../types'

export function IncidentsPage() {
  const { token, user } = useAuth(); const businessId = user.businessId; const period = useMemo(() => { const to = new Date(); const from = new Date(); from.setMonth(from.getMonth() - 3); return { from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) } }, [])
  const path = `/api/businesses/${businessId}/incidents`; const incidents = useApiData<Incident[]>(`${path}?from=${period.from}&to=${period.to}`, []); const employees = useApiData<Employee[]>(`/api/businesses/${businessId}/employees`, [])
  const [modal, setModal] = useState<'create' | 'resolve' | null>(null); const [selected, setSelected] = useState<Incident | null>(null); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { if (modal === 'create') await api(path, { method: 'POST', body: JSON.stringify({ employeeId: Number(data.get('employeeId')), incidentDate: data.get('incidentDate'), type: data.get('type'), detectedMinutes: data.get('detectedMinutes') ? Number(data.get('detectedMinutes')) : null, notes: data.get('notes') || null }) }, token); else await api(`${path}/${selected?.id}/resolve`, { method: 'POST', body: JSON.stringify({ status: data.get('status'), notes: data.get('notes') || null }) }, token); setModal(null); await incidents.reload() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar la incidencia') } }
  return <div className="page"><PageHeader eyebrow="Excepciones" title="Incidencias" description="Registrá y resolvé ausencias, llegadas tarde y salidas anticipadas." actions={<button className="button primary" onClick={() => { setSelected(null); setModal('create') }}><Plus size={18} /> Registrar</button>} />{error && <Notice message={error} />}{incidents.loading ? <Loading /> : incidents.data.length === 0 ? <Empty title="Sin incidencias" text="No se registraron excepciones en el último trimestre." /> : <div className="table-wrap"><table><thead><tr><th>Empleado</th><th>Fecha</th><th>Tipo</th><th>Tiempo</th><th>Estado</th><th></th></tr></thead><tbody>{incidents.data.map((item) => <tr key={item.id}><td><strong>{item.employeeName}</strong></td><td>{formatDate(item.incidentDate)}</td><td>{item.type.replaceAll('_', ' ')}</td><td>{minutes(item.detectedMinutes)}</td><td><StatusBadge status={item.status} /></td><td>{item.status === 'DETECTED' && <button className="icon-button success" title="Resolver" onClick={() => { setSelected(item); setModal('resolve') }}><CheckCircle2 size={18} /></button>}</td></tr>)}</tbody></table></div>}{modal && <Modal title={modal === 'create' ? 'Registrar incidencia' : 'Resolver incidencia'} onClose={() => setModal(null)}><form className="form-grid" onSubmit={submit}>{error && <div className="full"><Notice message={error} /></div>}{modal === 'create' ? <><label className="full">Empleado<select name="employeeId" required>{employees.data.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.firstName} {item.lastName}</option>)}</select></label><label>Fecha<input name="incidentDate" type="date" max={new Date().toISOString().slice(0, 10)} defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Tipo<select name="type"><option value="ABSENCE">Ausencia</option><option value="LATE_ARRIVAL">Llegada tarde</option><option value="EARLY_DEPARTURE">Salida anticipada</option></select></label><label>Minutos detectados<input name="detectedMinutes" type="number" min="1" /></label></> : <label className="full">Resolución<select name="status"><option value="CONFIRMED">Confirmada</option><option value="JUSTIFIED">Justificada</option><option value="DISMISSED">Descartada</option></select></label>}<label className="full">Notas<textarea name="notes" rows={3} /></label><div className="modal-actions full"><button type="button" className="button ghost" onClick={() => setModal(null)}>Cancelar</button><button className="button primary">Guardar</button></div></form></Modal>}</div>
}
