import { KeyRound, Pencil, Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useAuth } from '../../auth/AuthContext'
import { Empty, Loading, Notice } from '../../components/Feedback'
import { Modal } from '../../components/Modal'
import { PageHeader } from '../../components/PageHeader'
import { StatusBadge } from '../../components/StatusBadge'
import { useApiData } from '../../hooks/useApi'
import { api } from '../../lib/api'
import { relativeTime } from '../../lib/format'
import type { Terminal } from '../../types'

interface TerminalCredentials { terminal: Terminal; secret: string }
export function TerminalsPage() {
  const { token, user } = useAuth(); const path = `/api/businesses/${user.businessId}/terminals`; const terminals = useApiData<Terminal[]>(path, []); const [editing, setEditing] = useState<Terminal | null | undefined>(undefined); const [credentials, setCredentials] = useState<TerminalCredentials | null>(null); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { if (editing) { await api(`${path}/${editing.id}`, { method: 'PUT', body: JSON.stringify({ name: data.get('name'), active: data.get('active') === 'on' }) }, token) } else { setCredentials(await api<TerminalCredentials>(path, { method: 'POST', body: JSON.stringify({ name: data.get('name'), identifier: data.get('identifier') }) }, token)) } setEditing(undefined); await terminals.reload() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar') } }
  async function rotate(item: Terminal) { if (!window.confirm(`¿Rotar el secreto de ${item.name}? El anterior dejará de funcionar.`)) return; try { setCredentials(await api<TerminalCredentials>(`${path}/${item.id}/rotate-secret`, { method: 'POST' }, token)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo rotar') } }
  return <div className="page"><PageHeader eyebrow="Dispositivos" title="Terminales" description="Credenciales independientes para los puntos de marcación." actions={<button className="button primary" onClick={() => setEditing(null)}><Plus size={18} /> Nueva terminal</button>} />{error && <Notice message={error} />}{terminals.loading ? <Loading /> : terminals.data.length === 0 ? <Empty title="Sin terminales" text="Creá una terminal para habilitar marcaciones en el local." /> : <div className="card-grid">{terminals.data.map((item) => <article className="entity-card" key={item.id}><div className="entity-icon"><KeyRound /></div><div><h3>{item.name}</h3><code>{item.identifier}</code><p>Último uso: {relativeTime(item.lastSeenAt)}</p></div><StatusBadge status={item.active ? 'CONFIRMED' : 'CANCELLED'} /><div className="row-actions"><button className="icon-button" onClick={() => rotate(item)} title="Rotar secreto"><KeyRound size={17} /></button><button className="icon-button" onClick={() => setEditing(item)} title="Editar"><Pencil size={17} /></button></div></article>)}</div>}{editing !== undefined && <Modal title={editing ? 'Editar terminal' : 'Nueva terminal'} onClose={() => setEditing(undefined)}><form className="form-stack" onSubmit={submit}>{error && <Notice message={error} />}<label>Nombre<input name="name" defaultValue={editing?.name} required /></label>{!editing && <label>Identificador<input name="identifier" placeholder="caja-principal" pattern="[A-Za-z0-9._-]+" required /></label>}{editing && <label className="check"><input name="active" type="checkbox" defaultChecked={editing.active} /> Terminal activa</label>}<div className="modal-actions"><button type="button" className="button ghost" onClick={() => setEditing(undefined)}>Cancelar</button><button className="button primary">Guardar</button></div></form></Modal>}{credentials && <Modal title="Guardá estas credenciales" onClose={() => setCredentials(null)}><div className="credential-box"><p>El secreto se muestra una sola vez. Configuralo ahora en el dispositivo.</p><label>Comercio<code>{user.businessId}</code></label><label>Terminal<code>{credentials.terminal.identifier}</code></label><label>Secreto<code>{credentials.secret}</code></label></div><div className="modal-actions"><button className="button primary" onClick={() => setCredentials(null)}>Ya las guardé</button></div></Modal>}</div>
}
